-- Migration: Created the database schema for GreenPulse, including tables for users, plants, plant_posts, communities, achievements, and mood_logs. Enabled Row Level Security (RLS) and policies for secure data access. This supports all core features like user profiles, plant management, social feeds, gamification, and wellness tracking.
-- Executed at: 2025-11-03T02:55:58Z
-- Generated by AI Agent

CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT,
  email TEXT UNIQUE,
  avatar TEXT DEFAULT 'https://via.placeholder.com/150',
  points INTEGER DEFAULT 0,
  level INTEGER DEFAULT 1,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile" ON users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON users FOR UPDATE USING (auth.uid() = id);

CREATE TABLE plants (
  id SERIAL PRIMARY KEY,
  name TEXT,
  species TEXT,
  owner_id UUID REFERENCES users(id),
  qr_code TEXT UNIQUE,
  mood TEXT DEFAULT 'Happy',
  emoji TEXT DEFAULT '🌱',
  growth_level INTEGER DEFAULT 1,
  image TEXT DEFAULT 'https://via.placeholder.com/150',
  care_history JSONB DEFAULT '[]',
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE plants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own plants" ON plants FOR SELECT USING (auth.uid() = owner_id);
CREATE POLICY "Users can manage their own plants" ON plants FOR ALL USING (auth.uid() = owner_id);

CREATE TABLE plant_posts (
  id SERIAL PRIMARY KEY,
  plant_id INTEGER REFERENCES plants(id),
  user_id UUID REFERENCES users(id),
  content TEXT,
  image TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE plant_posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public posts" ON plant_posts FOR SELECT USING (true);
CREATE POLICY "Users can create posts" ON plant_posts FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE TABLE communities (
  id SERIAL PRIMARY KEY,
  name TEXT,
  members INTEGER DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE communities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public communities" ON communities FOR SELECT USING (true);

CREATE TABLE achievements (
  id SERIAL PRIMARY KEY,
  user_id UUID REFERENCES users(id),
  badge_type TEXT,
  earned_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE achievements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their achievements" ON achievements FOR SELECT USING (auth.uid() = user_id);

CREATE TABLE mood_logs (
  id SERIAL PRIMARY KEY,
  user_id UUID REFERENCES users(id),
  mood TEXT,
  date DATE DEFAULT CURRENT_DATE
);

ALTER TABLE mood_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their mood logs" ON mood_logs FOR ALL USING (auth.uid() = user_id);
