// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: mkqgelczdlbxbybgfksw

class SupabaseConfig {
  static const String supabaseUrl = 'https://mkqgelczdlbxbybgfksw.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rcWdlbGN6ZGxieGJ5Ymdma3N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxMDc2ODUsImV4cCI6MjA3NzY4MzY4NX0.VSrRG5wx6DBGpXb3H6fd-gF802tb1Yei9PYXjpHtK5k';
}
